WIP: Matchmaker: Use Connect for gRPC-compatible RPC
phaux/game-api pull request #2
Opened 2022-07-23 22:05 UTC by szabba

2022-07-23 23:43 UTC, szabba commented on matchmaker/rpc/v1/api.proto
> +syntax = "proto3";
@phaux If we followed this route, this file + the README I plan to add would be the most interesting to you.

2022-07-24 00:20 UTC, phaux commented
Add README with instructions how to run and example `curl` requests and responses

2022-07-27 17:21 UTC, phaux requested changes

2022-07-27 17:21 UTC, phaux commented on matchmaker/README.markdown
> +   - The [JSON <-> Protobuf mapping] is documented separately
Can we generate HTTP API description and include it here or a separate md file?

2022-07-27 17:21 UTC, phaux commented on matchmaker/README.markdown
> +## File structure
Readme should be more concise and this section isn't needed at all IMO

2022-07-27 17:21 UTC, phaux commented on matchmaker/README.markdown
> +`ZONEINFO` | Preferred [tz database] location. See [`time.LoadLocation`] | `/zoneinfo` (default: empty)
Server location shouldn't matter

2022-07-27 17:35 UTC, phaux commented
I think the readme structure should be:

- Usage
    1. List of required tools and their versions
    2. How to build 
    3. List of config files, env vars, cmd line args
    4. How to run 
    5. Description of exposed API
- Development
    - List of extra required tools if any
    - How to run in watch mode if applicable
    - What to run before commit (fmt, lint, generate)
    - How to deploy (in the future)
 
Things that will turn out to be the same for all packages in monorepo will be factored out to the main README later.

2022-07-28 14:15 UTC, szabba commented on matchmaker/buf.yaml
> +    - DEFAULT
Add linting rule that only allows unary RPCs - streaming is a whole bunch of problems we don't need to get into.

2022-07-28 14:16 UTC, szabba commented
Make sure to regenerate the code in `matchmaker/gen/` before merging.

2022-07-28 14:22 UTC, szabba commented on matchmaker/README.markdown
> +   - The [JSON <-> Protobuf mapping] is documented separately
There's no preexisting tool that just does that. We could write one, but that's a siginificant effort and OT for this PR/repository.

2022-07-28 14:25 UTC, szabba commented on matchmaker/README.markdown
> +`ZONEINFO` | Preferred [tz database] location. See [`time.LoadLocation`] | `/zoneinfo` (default: empty)
(See also #3 for doing the same with the trusted CA root certificate pool.)

2022-07-29 15:59 UTC, szabba commented
> Make sure to regenerate the code in `matchmaker/gen/` before merging.

I've added a basic pipeline workkflow, since the Earthly build verifies it automatically already.

2022-07-29 16:15 UTC, phaux commented on matchmaker/README.markdown
> +   - The [JSON <-> Protobuf mapping] is documented separately
Then write one by hand

2022-07-29 16:21 UTC, szabba commented on matchmaker/README.markdown
> +## File structure
I've reorganized the readme roughly along the lines of the other, longer comment. How is it now?

2022-07-29 16:35 UTC, szabba commented on matchmaker/README.markdown
> +   - The [JSON <-> Protobuf mapping] is documented separately
Let's talk about incentives here:
- OpenAPI is relatively general and unopinionated in what it describes, but is (I feel): 
    - very verbose, 
    - makes people care about _mostly_ uninteresting details.
- Manually written examples _will_ go out of sync. It's just a matter of time.
- A tool for generating swagger out of the proto spec is not readily available.
- I think I've found less effort-intensive way to implement generating the curl samples with [`http2curl`](https://pkg.go.dev/github.com/moul/http2curl) but I'd prefer to deliver that in a separate PR.

2022-07-29 20:19 UTC, phaux approved these changes

2022-07-29 20:21 UTC, szabba commented on matchmaker/buf.yaml
> +    - DEFAULT
Done.

2022-07-29 20:26 UTC, merged